# Generated by Django 5.1.4 on 2024-12-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedulelecturer',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='next_of_kin0',
        ),
        migrations.AddField(
            model_name='courseschedulelecturer',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedule_lecturers', to='ucc.staff'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='kin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin0', to='ucc.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='next_of_kin1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ucc.nextofkin'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='home_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='work_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='courseprerequisite',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_prerequisites0', to='ucc.course'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='ucc.coursesection'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='ucc.location'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='ucc.semester'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='ucc.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='ucc.login'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='ucc.position'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ucc.programofstudy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ucc.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ucc.contactdetails'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='ucc.title'),
        ),
    ]
