# Generated by Django 5.1.4 on 2024-12-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucc', '0005_student_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
