# Generated by Django 5.1.4 on 2024-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucc', '0006_remove_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='courseWorkGrade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='finalExamProjectGrade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='finalGrade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
