# Generated by Django 5.1.4 on 2024-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucc', '0007_alter_courseenrollment_courseworkgrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='finalGrade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='courseWorkGrade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='finalExamProjectGrade',
            field=models.FloatField(),
        ),
    ]
