# Generated by Django 5.1.4 on 2024-12-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucc', '0008_remove_courseenrollment_finalgrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='letterGrade',
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='courseWorkGrade',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='finalExamProjectGrade',
            field=models.FloatField(default=50),
        ),
    ]
